name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: venv

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Service Account file
        working-directory: ./projeto_prod
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT }}' > service-account.json

      - name: Install dbt packages
        working-directory: ./projeto_prod
        run: dbt deps

      - name: Validate dbt project
        working-directory: ./projeto_prod
        env:
          GCP_DEV_PROJECT: ${{ secrets.GCP_DEV_PROJECT }}
          DBT_DEV_SCHEMA: ${{ secrets.DBT_DEV_SCHEMA }}
          GCP_DEV_KEYFILE_PATH: service-account.json
        run: dbt debug --profiles-dir .

      - name: Build dbt project
        working-directory: ./projeto_prod
        env:
          GCP_DEV_PROJECT: ${{ secrets.GCP_DEV_PROJECT }}
          DBT_DEV_SCHEMA: ${{ secrets.DBT_DEV_SCHEMA }}
          GCP_DEV_KEYFILE_PATH: service-account.json
        run: dbt build --profiles-dir .

      - name: Generate dbt docs
        working-directory: ./projeto_prod
        env:
          GCP_DEV_PROJECT: ${{ secrets.GCP_DEV_PROJECT }}
          DBT_DEV_SCHEMA: ${{ secrets.DBT_DEV_SCHEMA }}
          GCP_DEV_KEYFILE_PATH: service-account.json
        run: dbt docs generate --profiles-dir .

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./projeto_prod/target

  deploy:
    needs: build

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4